name: Quill get artifact
description: Downloads Quill's build artifact and unarchive it
inputs:
  working-directory:
    description: Quill repo directory
runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: quill-artifact
        path: ${{ inputs.working-directory }}

    - name: Unpack artifact
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: 7z x quill-artifact.zip
