name: Quill functional tests step
description: Functional tests step in the Quill checks workflow
runs:
  using: composite
  steps:
    - name: Prepare Quill environment
      uses: ./.github/actions/quill/common/prepare

    - name: Get artifact
      uses: ./.github/actions/quill/common/get-artifact

    - name: Copy dist
      shell: bash
      run: pnpm run copy-dist

    - name: Run functional tests
      shell: bash
      run: pnpm run test:functional -- --browsers="chrome:headless"
