name: Quill prepare
description: Making ready Quill source code for the next job steps
inputs:
  node-version:
    description: Node.js version
    required: true
    default: '18'
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
