name: Functional tests

on:
  push:
    branches: [ func ]
  pull_request:
    branches: [ func ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: sudo apt-get install xvfb
    - run: npm ci
    - run: npm run build
    - run: npm run copy-dist
    - name: HTTP Server Action
      uses: Eun/http-server-action@v1.0.3
      with:
        directory: ./test/functional/example
    - run: xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" npm run test:functional
