name: Functional tests

on:
  push:
    branches: [ func ]
  pull_request:
    branches: [ func ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run copy-dist
    - name: HTTP Server Action
      uses: Eun/http-server-action@v1.0.3
      with:
        directory: ./test/functional/example
    - run: npm run test:functional
