name: Html Editor

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-quill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v3

      - name: Build package
        uses: ./.github/actions/quill/steps/build-package

  build:
    needs: build-quill
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: build ${{ matrix.branch }}
    strategy:
      fail-fast: false
      matrix:
        branch: [22_2, 22_1]
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v3
        with:
          path: quill-repo

      - name: Build
        uses: ./quill-repo/.github/actions/html-editor/steps/build
        with:
          branch: ${{ matrix.branch }}

  qunit:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: qunit ${{ matrix.branch }}
    strategy:
      fail-fast: false
      matrix:
        branch: [22_2, 22_1]
        test-suite: [ui.htmlEditor]
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v3
        with:
          path: quill-repo

      - name: QUnit tests
        uses: ./quill-repo/.github/actions/html-editor/steps/qunit-tests
        with:
          branch: ${{ matrix.branch }}
          test-suite: ${{ matrix.test-suite }}

  testcafe:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: testcafe ${{ matrix.branch }}
    strategy:
      fail-fast: false
      matrix:
        branch: [22_2, 22_1]
        test-suite: [
          { componentFolder: 'htmlEditor', quarantineMode: false },
        ]
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v3
        with:
          path: quill-repo

      - name: Testcafe tests
        uses: ./quill-repo/.github/actions/html-editor/steps/testcafe-tests
        with:
          branch: ${{ matrix.branch }}
          component-directory: ${{ matrix.test-suite.componentFolder }}
          quarantine-mode: ${{ matrix.test-suite.quarantineMode }}




