name: Publish

on:
  push:
    branches:
      - ci-dry-run-git-status

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v6
        with:
          ref: refs/heads/master
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/quill/steps/build

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Pack
        run: |
          package_tgz=$(pnpm pack --json | jq -er 'if type=="array" then .[0].filename else .filename end')
          echo "PACKAGE_TGZ=$package_tgz" >> "$GITHUB_ENV"

      - name: Git Status
        run: |
          git branch --show-current
          git status

      - name: Publish to NPM (dry-run)
        run: pnpm publish "$PACKAGE_TGZ" --dry-run --publish-branch master
