name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Publishing version (tag name)
      dry-run:
        description: 'Run in dry-run mode (no actual publish)'
        type: boolean
        default: false

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npmjs
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.version }}

      - name: Build
        uses: ./.github/actions/quill/steps/build

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Pack
        run: |
          package_tgz=$(pnpm pack --json | jq -er 'if type=="array" then .[0].filename else .filename end')
          echo "PACKAGE_TGZ=$(realpath "$package_tgz")" >> "$GITHUB_ENV"

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: ${{ env.PACKAGE_TGZ }}
          if-no-files-found: error
          retention-days: 14

      - name: Build SBOM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm set //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN"
          cd tools/make-sbom && pnpm install --frozen-lockfile && pnpm dx-make-sbom ../../ dist/ "devextreme-quill($PACKAGE_TGZ)"

      - name: Upload SBOM
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: tools/make-sbom/dist
          if-no-files-found: error
          retention-days: 14

      - name: Validate SBOM
        uses: DevExpress/github-actions/validate-sbom@5034a6d5e0fd18fc2826ed20a5140f9c83b8994f
        with:
          input-file: tools/make-sbom/dist/devextreme-quill.cdx.json

      - name: Publish to NPM
        run: pnpm publish "$PACKAGE_TGZ" --provenance ${{ inputs['dry-run'] && '--dry-run' || '' }}

      - name: Setup NPM tags
        if: ${{ !inputs['dry-run'] }}
        run: |
          npm dist-tag add devextreme-quill@${{ inputs.version }} 24_1
          npm dist-tag add devextreme-quill@${{ inputs.version }} 24_2
          npm dist-tag add devextreme-quill@${{ inputs.version }} 25_1
