name: SBOM

on:
  push:
    branches:
      - sbom-dev

permissions:
  contents: read
  packages: read

jobs:
  sbom:
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'sbom-dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/quill/steps/build

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Pack
        run: |
          package_tgz=$(pnpm pack --json | jq -er 'if type=="array" then .[0].filename else .filename end')
          echo "PACKAGE_TGZ=$(realpath "$package_tgz")" >> "$GITHUB_ENV"

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: ${{ env.PACKAGE_TGZ }}
          if-no-files-found: error
          retention-days: 1

      - name: Build SBOM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm set //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN"
          cd tools/make-sbom && pnpm install --frozen-lockfile && pnpm dx-make-sbom ../../ dist/ "devextreme-quill($PACKAGE_TGZ)"

      - name: Upload SBOM
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: tools/make-sbom/dist
          if-no-files-found: error
          retention-days: 1

      # - name: Break SBOM
      #   run: |
      #     jq '.specVersion += "aaa"' tools/make-sbom/dist/devextreme-quill.cdx.json > t && mv t tools/make-sbom/dist/devextreme-quill.cdx.json

      - name: Validate SBOM
        uses: mpreyskurantov/github-actions/validate-sbom@sbom-val-dev
        with:
          input-file: tools/make-sbom/dist/devextreme-quill.cdx.json

      - name: Publish to NPM (dry-run)
        run: pnpm publish "$PACKAGE_TGZ" --no-git-checks --dry-run
