name: SBOM

on:
  push:
    branches:
      - sbom-dev

permissions:
  contents: read
  packages: read

jobs:
  build:
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'sbom-dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/quill/steps/build

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Pack
        run: |
          package_tgz=$(pnpm pack --json | jq -er '.filename')
          echo "PACKAGE_TGZ=$package_tgz" >> "$GITHUB_ENV"

      - name: Print packed file
        run: echo "$PACKAGE_TGZ"

      - name: Build SBOMs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm set //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN"
          cd tools/make-sbom && pnpm install --frozen-lockfile && pnpm run make-sbom-hashed

      # - name: Break SBOMs
      #   run: |
      #     jq '.specVersion += "aaa"' tools/make-sbom/dist/devextreme-quill.cdx.json > t && mv t tools/make-sbom/dist/devextreme-quill.cdx.json

      - name: Validate SBOMs
        uses: mpreyskurantov/github-actions/validate-sbom@adcd7cdfb78f01e2e11678673def84ab367ddd25
        with:
          input-file: tools/make-sbom/dist/devextreme-quill.cdx.json

      - name: Upload SBOMs
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: tools/make-sbom/dist
          retention-days: 2
