name: TestCafe tests

on: [push, pull_request]

jobs:
  testcafe:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build

    - name: Run TestCafe tests
      uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome test/testcafe"
